### PR TITLE
convert libwasi to libcwasi

### PR DESCRIPTION
**Pull request by SamuraiCrow**
Since Python created with C is CPython, I figured CWASI is WASI created with C.  Further addresses #39 by renaming libwasi.so to libcwasi.so as well.

### CODE REVIEW

**Comment by turbolent** [comment]
Not quite sure, but is this renaming necessary in the project itself? If there is a naming clash on a particular system, can't the packaging be done so that the library is *installed* with a different name?

**Comment by SamuraiCrow** [comment]
The dlopen needs to match the filename.

**Comment by SamuraiCrow** [comment]
If a blogger or somebody else does a review of W2C2 in their writing, they are likely to compare the quaility of code side-by-side with WAsm2C.  Whether the intended audience is modern platforms or not, a name collision between W2C2 and WABT's libWASI is going to look bad.  Also, as mentioned previously, the dlopen or equivalent OS command to load the shared object must look at the proper filename or it will not find it.  I don't mind if you choose a different filename than libCWASI.so as long as it doesn't collide with the existing WAsm2C runtime.

**Comment by turbolent** [comment]
@SamuraiCrow Thank you for opening the PR and the explanation! Could we maybe name it `w2c2wasi` to make it more explicit what it can be used with?

**Comment by SamuraiCrow** [comment]
Certainly!  I'll rework the PR soon.

**Pull request closed without merging**
