### PR TITLE
Buildfix using Submake workers

### PR DESCRIPTION
**Pull request by SamuraiCrow**
I've figured out a way to partition the W2C2 code generation and the GNU Make manipulations during a parallel build such that `make -j8` will build everything without the added `make clang.c` step at the beginning and likewise Python.  Before I spend any more time with using the Submake workers on any additional examples, please let me know what you think.

### CODE REVIEW

**Review by turbolent — COMMENTED** [review]
How does the new approach differ from the old? Aren't they equivalent? (I only know the basics of Makefiles)

**Comment by SamuraiCrow** [comment]
By placing the section of the makefile in a separate file, I was able to make the submake dependant on the success of the original makefile where W2C2 was invoked as a generator of source.

During a parallel build, the rules referring to the generated files from W2C2 would attempt to build .c files that were still being written because the directory contents were cached at the time of the invocation of the original call of the make utility.  Also, the variables defined at the time of the original make invocation couldn't be redefined without adding a new make invocation.

The net result is that `make -j8` requires no separate invocation to `make clang.c` to block the parallel build until the W2C2's C source generation is complete.  (It took some figuring and experiments to figure out why that extra step was previously needed.)

**Review by turbolent — APPROVED** [review]
Nice, thank you!

**Comment by SamuraiCrow** [comment]
I saw that Rust-wasm and Swift-wasm had the same pattern in their `Makefile`s so I applied the same changes to theirs.  There isn't a Haiku version of Swift and I don't have Rust installed now so I hope I didn't break anything.

**Pull request merged**
